version: '3'
services:
  frontend:
    container_name: nginx
    # restart: always
    image: nginx
    build:
      context: ./frontend
      dockerfile: .docker/nginx.dockerfile
    volumes:
      - ./frontend/dist:/usr/share/nginx/html
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - mongodb
      - backend
  
  mongodb:
    container_name: mongodb
    image: "mongo:latest"
    # restart: always
    networks:
      - app-network
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mihape-database
      MONGO_INITDB_ROOT_PASSWORD: Rahasia10mihape

  backend:
    build:
      context: .
    # restart: always
    volumes:
      - .:/var/www/mihape
    depends_on:
      - mongodb
    environment:
      - NODE_ENV=production
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:./node_modules/.bin
    ports:
      - "3000:3000"
    networks:
      - app-network
  
networks:
  app-network:
    driver: bridge