version: '3'
services:
  frontend:
    container_name: mihape-frontend-nginx
    restart: always
    image: nginx:latest
#    build:
#      context: ./frontend
    volumes:
      - ./frontend/dist:/usr/share/nginx/html
      - ./frontend/.docker/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/dh-param/dhparam-2048.pem:/etc/ssl/certs/dhparam-2048.pem
      - /docker-volumes/etc/letsencrypt/live/mihape.com/fullchain.pem:/etc/letsencrypt/live/mihape.com/fullchain.pem
      - /docker-volumes/etc/letsencrypt/live/mihape.com/privkey.pem:/etc/letsencrypt/live/mihape.com/privkey.pem
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    networks:
      - docker-network
  
  backend:
    container_name: mihape-backend
    build:
      context: .
    restart: always
    environment:
      - NODE_ENV=production
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:./node_modules/.bin
    ports:
      - "3000:3000"
    networks:
      - docker-network
  
networks:
  docker-network:
    driver: bridge
